// Run with Playwright installed, or set PLAYWRIGHT_MODULE to its index.mjs path.
import assert from 'node:assert/strict';
import {mkdir, writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
const {chromium} = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const out = process.env.INVOICE_TEST_OUTPUT || '/tmp/fw-invoice-check';
await mkdir(out,{recursive:true});
const browser = await chromium.launch({headless:true, channel:process.env.PLAYWRIGHT_CHANNEL || "chrome"});
try {
  const context = await browser.newContext({viewport:{width:1512,height:1100},acceptDownloads:true});
  await context.addInitScript(() => {window.__FW_TEST__ = {};});
  const page = await context.newPage();
  const errors = [], external = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => {if (/^https?:/.test(r.url())) external.push(r.url());});
  page.on('dialog', d => d.accept());
  const url = pathToFileURL(resolve('tools/invoice/index.html')).href;
  await page.goto(url);
  const field = name => page.locator(`[data-field="${name}"]`);
  await field('customer').fill('Acme Studio');
  await field('email').fill('client@example.com');
  await field('address').fill('123 Ocean Avenue\nHuntington Beach, CA 92648');
  await field('project').fill('Website design & launch');
  await page.locator('[data-key="rate"]').fill('1250.50');
  await page.locator('[data-key="qty"]').fill('2');
  await field('discount').fill('10');
  await field('tax').fill('8.25');
  await page.locator('#add-item').click();
  await page.locator('[data-key="description"]').nth(1).fill('Hosting setup & handoff');
  await page.locator('[data-key="rate"]').nth(1).fill('100');
  const readDoc = () => page.evaluate(() => {const s=JSON.parse(localStorage.getItem('fw-business-desk-v1'));return s.documents.find(d=>d.id===s.activeId);});
  let doc = await readDoc();
  const totals = await page.evaluate(d => window.__FW_TEST__.api.totals(d), doc);
  assert.deepEqual(totals,{subtotal:260100,discount:26010,tax:19312,total:253402,paid:0,balance:253402,credit:0});
  for (const rate of [0.5,50001]) {
    const invalidLink = await page.evaluate(d => window.__FW_TEST__.api.paymentLink(d), {...doc,discount:0,tax:0,items:[{description:'Test',qty:1,rate}]});
    assert.equal(invalidLink,'');
  }
  const quoteId = doc.id;
  await page.reload();
  assert.equal(await field('customer').inputValue(),'Acme Studio');
  await page.locator('#convert').click();
  doc=await readDoc();
  assert.equal(doc.type,'invoice');
  assert.notEqual(doc.id,quoteId);
  assert.equal(await page.locator('.document-card').count(),2);
  await field('paid').fill('500');
  assert.match(await page.locator('.balance').innerText(),/2,034.02/);
  const link = new URL(await page.locator('.payment-box a').first().getAttribute('href'));
  assert.equal(link.searchParams.get('amount'),'2034.02');
  assert.match(link.searchParams.get('for'),new RegExp(doc.number));
  assert.equal(link.href.includes('client%40'),false);
  await page.evaluate(() => window.scrollTo(0,0));
  await page.screenshot({path:out+'/desktop.png',fullPage:true});
  await page.pdf({path:out+'/invoice.pdf',printBackground:true,preferCSSPageSize:true});
  await field('currency').selectOption('EUR');
  assert.equal(await page.locator('.payment-box').count(),0);
  await field('paymentMode').selectOption('custom');
  await field('paymentUrl').fill('javascript:alert(1)');
  assert.equal(await page.locator('.payment-box').count(),0);
  await field('paymentUrl').fill('https://buy.stripe.com/example');
  assert.equal(await page.locator('.payment-box a').first().getAttribute('href'),'https://buy.stripe.com/example');
  await field('customer').fill('<img src=x onerror="alert(1)">');
  assert.equal(await page.locator('#paper img[src="x"]').count(),0);
  await field('customer').fill('Acme Studio');
  await field('currency').selectOption('USD');
  await field('paymentMode').selectOption('website');
  await field('paid').fill('3000');
  assert.match(await page.locator('.balance').innerText(),/Credit balance/);
  assert.equal(await page.locator('.payment-box').count(),0);
  await field('paid').fill('500');
  // Incomplete drafts must survive a reload.
  await field('issued').fill('');
  await page.reload();
  assert.equal(await field('issued').inputValue(),'');
  await field('issued').fill('2026-09-24');
  await field('due').fill('2026-10-08');
  await page.locator('#duplicate').click();
  assert.equal((await readDoc()).paid,0);
  const downloaded = page.waitForEvent('download'); await page.locator('#backup').click();
  const backup = await downloaded; await backup.saveAs(out+'/backup.json');
  await page.locator('#import-file').setInputFiles(out+'/backup.json');
  await page.waitForFunction(() => document.querySelectorAll('.document-card').length === 6);
  await writeFile(out+'/bad.json',JSON.stringify({version:1,activeId:'x',documents:[{id:'x'}]}));
  await page.locator('#import-file').setInputFiles(out+'/bad.json');
  await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('not a valid'));
  assert.equal(await page.locator('.document-card').count(),6);
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:out+'/mobile.png',fullPage:true});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
  // Long documents should paginate, retaining totals and payment information.
  await page.evaluate(() => {
    const s=JSON.parse(localStorage.getItem('fw-business-desk-v1'));
    const d=s.documents.find(d=>d.id===s.activeId);
    d.items=Array.from({length:45},(_,i)=>({description:`Deliverable ${i+1}: Website design, content, accessibility and handoff details.`,qty:1,rate:50}));
    localStorage.setItem('fw-business-desk-v1',JSON.stringify(s));
  });
  await page.reload();
  await page.pdf({path:out+'/multipage.pdf',printBackground:true,preferCSSPageSize:true});
  assert.deepEqual(errors,[]);
  assert.deepEqual(external,[]);
  // Storage denial must leave the app usable and communicate unsaved state.
  const blocked = await browser.newContext();
  await blocked.addInitScript(() => {Storage.prototype.getItem=()=>{throw new Error('blocked')};Storage.prototype.setItem=()=>{throw new Error('blocked')};});
  const blockedPage=await blocked.newPage(); await blockedPage.goto(url);
  assert.match(await blockedPage.locator('#save-status').innerText(),/Not saved/);
  await blockedPage.locator('[data-field="customer"]').fill('Still editable');
  assert.match(await blockedPage.locator('#paper').innerText(),/Still editable/);
  console.log('PASS: calculations, persistence, conversion, partial payment, links, currency, escaping, credit, draft recovery, duplication, backup import/export, invalid imports, mobile layout, offline operation, PDF generation, storage failure.');
  console.log(`Visual/PDF output: ${out}`);
} finally {await browser.close();}
